# Generated by Django 3.1.2 on 2020-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Casa', 'casa'), ('Departamento', 'departamento'), ('Habitacion', 'habitacion')], max_length=12)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField()),
                ('metros_cubiertos', models.IntegerField()),
                ('metros_descubiertos', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('cochera', models.BooleanField()),
                ('cap_cochera', models.IntegerField()),
                ('cant_baños', models.IntegerField()),
            ],
            options={
                'ordering': ('tipo',),
            },
        ),
    ]
