# Generated by Django 3.1.2 on 2020-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'masculino'), ('Femenino', 'femenino')], max_length=9)),
                ('domicilio', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre_completo',),
            },
        ),
    ]
